#!/bin/bash

echo "📸 Screenshot Guide for Sight App"
echo "=================================="
echo ""
echo "The app should now be running in your menu bar (look for the eye icon 👁)."
echo ""
echo "Please take these screenshots manually:"
echo ""
echo "1. MENU BAR DASHBOARD:"
echo "   - Click the eye icon in your menu bar"
echo "   - Press Cmd+Shift+4, then Space"
echo "   - Click the popover window"
echo "   - Save as: dashboard.png"
echo ""
echo "2. BREAK OVERLAY:"
echo "   - Click 'Take Break' in the menu"
echo "   - Press Cmd+Shift+3 (full screen)"
echo "   - Save as: overlay.png"
echo ""
echo "3. PREFERENCES:"
echo "   - Right-click menu bar icon → Preferences"
echo "   - Press Cmd+Shift+4, then Space"
echo "   - Click the preferences window"
echo "   - Save as: preferences.png"
echo ""
echo "4. ONBOARDING (if still showing):"
echo "   - Press Cmd+Shift+4, then Space"
echo "   - Click the onboarding window"
echo "   - Save as: onboarding.png"
echo ""
echo "Save all screenshots to:"
echo "/Users/spy/Desktop/Sight/Resources/Screenshots/"
echo ""
echo "After taking screenshots, run:"
echo "  cd /Users/spy/Desktop/Sight"
echo "  git add Resources/Screenshots/*.png"
echo "  git commit -m 'docs: Add app screenshots'"
echo "  git push"
